trigger:
  branches:
    include:
      - main  # This will trigger the pipeline for pushes to the `main` branch.

pool:
  vmImage: 'ubuntu-latest'  # The agent VM image to use for the build.

variables:
  buildConfiguration: 'Release'

steps:
- task: UseRustToolInstaller@0
  inputs:
    versionSpec: '1.57.0'  # Specify the Rust version to use. Modify as needed.

- task: Checkout@2
  displayName: 'Checkout code'
  
- script: |
    rustup update  # Ensure Rust is up-to-date
    cargo build --release  # Build the project in release mode
  displayName: 'Build Rust project'

- script: |
    cargo test  # Run tests
  displayName: 'Run tests'
  
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'target/release'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish artifacts'
