config:
  "azure-native:location": eastus2
  "help:app": help
  "help:env": dev
  "help:location": eastus2
  "help:owneremail": ""
  "help:subscriptionId": 1234-5678-91011
  "help:tier": bronze
  "help:virtualSubnetworks": ","
environment:
  - meta
