config:
  "azure-native:location": eastus2
  "stillworks:app": stillworks
  "stillworks:env": prod
  "stillworks:location": eastus2
  "stillworks:owneremail": ""
  "stillworks:subscriptionId": 1234-5678-91011
  "stillworks:tier": platinum
  "stillworks:virtualSubnetworks": ","
environment:
  - meta
